// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfeGkjTa1l66Tk8ntYzoBe2viWO1r4vMU',
    appId: '1:884014883885:android:8c630fefcd27d0b28604a4',
    messagingSenderId: '884014883885',
    projectId: 'e-learning-10cbb',
    databaseURL: 'https://e-learning-10cbb-default-rtdb.firebaseio.com',
    storageBucket: 'e-learning-10cbb.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQAOg2IzELFBNKva32odtheMxnR_ozZQM',
    appId: '1:884014883885:web:1e208e2e897c8ed78604a4',
    messagingSenderId: '884014883885',
    projectId: 'e-learning-10cbb',
    authDomain: 'e-learning-10cbb.firebaseapp.com',
    databaseURL: 'https://e-learning-10cbb-default-rtdb.firebaseio.com',
    storageBucket: 'e-learning-10cbb.firebasestorage.app',
    measurementId: 'G-W46V4NETT5',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwbaTJJ3slrH6ujutYFq-4_ybTazP5rJ0',
    appId: '1:884014883885:ios:4c31c74988e2186f8604a4',
    messagingSenderId: '884014883885',
    projectId: 'e-learning-10cbb',
    databaseURL: 'https://e-learning-10cbb-default-rtdb.firebaseio.com',
    storageBucket: 'e-learning-10cbb.firebasestorage.app',
    iosBundleId: 'y',
  );

}