

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:my_flutter_app/presentation/bloc/auth_bloc/auth_bloc.dart';
import 'package:my_flutter_app/presentation/bloc/auth_bloc/auth_event.dart';
import 'package:my_flutter_app/presentation/bloc/auth_bloc/auth_state.dart';
import 'package:my_flutter_app/presentation/bloc/course/course_bloc.dart';
import 'package:my_flutter_app/presentation/routes/app_routes.dart';
import 'package:my_flutter_app/presentation/screens/auth/login_screen.dart';
import 'package:my_flutter_app/presentation/screens/home/home_screen.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Ensure this file exists and is generated by Firebase CLI
import 'package:flutter_dotenv/flutter_dotenv.dart';


void main() async {

   WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase before the app starts
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

   await dotenv.load(fileName: ".env");

  runApp(BlocProvider(
  create: (_)=>AuthBloc()..add(AuthCheckStatus()),
  child: const MyApp()));
}



class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<AuthBloc, AuthState>(
      builder: (context, state) {
        // if (state is ) {
        //   return const MaterialApp(
        //     home: Scaffold(
        //       body: Center(child: CircularProgressIndicator()),
        //     ),
        //   );
        // } else 
        if (state is AuthState && state.isAuthenticated) {
          // If logged in → go to Home
          return BlocProvider(
            create: (context) => CourseBloc(context.read<AuthBloc>()),
            child: MaterialApp.router(
              debugShowCheckedModeBanner: false,
              title: 'E-Learning App',
              theme: ThemeData(primarySwatch: Colors.indigo),
              routerConfig: appRouter,
            ),
          );
        } else {
          // Not logged in → go to Login
          return MaterialApp(
            debugShowCheckedModeBanner: false,
            title: 'E-Learning App',
            theme: ThemeData(primarySwatch: Colors.indigo),
            home: const LoginScreen(),
          );
        }
      },
    );
  }
}




// import 'dart:io';
// import 'package:flutter/material.dart';
// import 'package:my_flutter_app/custom/test.dart';
// import 'package:my_flutter_app/home_page.dart';
// import 'package:my_flutter_app/list_page.dart';
// import 'package:my_flutter_app/profile_page.dart';
// import 'package:my_flutter_app/quiz/QuizMain.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart'; // Ensure this file exists and is generated by Firebase CLI


// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   if(!Platform.isLinux){

//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );
//   }
//   else{
//    debugPrint("Running on Linux - Skipping Firebase Initialization");
//   }

//   runApp(const MyApp());
// }

// class MyApp extends StatelessWidget {
//   const MyApp({super.key});

//   // This widget is the root of your application.
//   @override
//   Widget build(BuildContext context) {
//     const String title = 'Flutter Demo Home Page';
//     return MaterialApp(
//       title: title,
//       debugShowCheckedModeBanner: false,
//       theme: ThemeData(
//         colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
//       ),
//       home: MyHomePage(title: title),
//     );
//   }
// }

// class MyHomePage extends StatefulWidget {
//   const MyHomePage({super.key, required this.title});

//   // This widget is the home page of your application. It is stateful, meaning
//   // that it has a State object (defined below) that contains fields that affect
//   // how it looks.

//   // This class is the configuration for the state. It holds the values (in this
//   // case the title) provided by the parent (in this case the App widget) and
//   // used by the build method of the State. Fields in a Widget subclass are
//   // always marked "final".

//   final String title;

//   @override
//   State<MyHomePage> createState() => _MyHomePageState();
// }

// class _MyHomePageState extends State<MyHomePage> {


  

//   int currentPageIndex = 0;

//   List<Widget> pages = [
//     const MainPage(),
//     const ProfilePage(),
//     const FormSection(),
//     const Quizmain(),
//     TextSection()
//   ];

//   @override
//   Widget build(BuildContext context) {
//     // This method is rerun every time setState is called, for instance as done
//     // by the _incrementCounter method above.

//     const NavigationDestination homeDestination = NavigationDestination(
//       icon: Icon(Icons.home),
//       label: 'Home',
//     );
//     const NavigationDestination settingsDestination = NavigationDestination(
//       icon: Icon(Icons.settings),
//       label: 'Settings',
//     );
//     const NavigationDestination QuizDestination = NavigationDestination(
//       icon: Icon(Icons.quiz),
//       label: 'Quiz',
//     );
//     const NavigationDestination viewProfile = NavigationDestination(
//       icon: Icon(Icons.people),
//       label: 'Profile',
//     );

//     //
//     // The Flutter framework has been optimized to make rerunning build methods
//     // fast, so that you can just rebuild anything that needs updating rather
//     // than having to individually change instances of widgets.
//     return  Scaffold(
//       appBar: AppBar(
//         // TRY THIS: Try changing the color here to a specific color (to
//         // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
//         // change color while the other colors stay the same.
//         backgroundColor: Theme.of(context).colorScheme.inversePrimary,
//         primary: true,
//         foregroundColor: Colors.white60,

        
//         // Here we take the value from the MyHomePage object that was created by
//         // the App.build method, and use it to set our appbar title.
//         title:  Text(widget.title,  style: TextStyle(color: const Color.fromARGB(255, 117, 89, 5)), semanticsIdentifier: 'appBarTitle', textAlign: TextAlign.center, textDirection: TextDirection.ltr, overflow: TextOverflow.ellipsis, maxLines: 1, softWrap: false, textScaleFactor: 1.0) ,
//       ),
//       // The body of the Scaffold is where the main content of the page goes.
//       // The Scaffold widget provides a default app bar, a body, and a floating

//       body: pages[currentPageIndex],
//       // body: Center(
//         // Center is a layout widget. It takes a single child and positions it
//         // in the middle of the parent.
//         // child: Column(
//           // Column is also a layout widget. It takes a list of children and
//           // arranges them vertically. By default, it sizes itself to fit its
//           // children horizontally, and tries to be as tall as its parent.
//           //
//           // Column has various properties to control how it sizes itself and
//           // how it positions its children. Here we use mainAxisAlignment to
//           // center the children vertically; the main axis here is the vertical
//           // axis because Columns are vertical (the cross axis would be
//           // horizontal).
//           //
//           // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
//           // action in the IDE, or press "p" in the console), to see the
//           // wireframe for each widget.
//           // mainAxisAlignment: MainAxisAlignment.center,
//           // children: <Widget>[
//           //   const Text('You have pushed the button this many times:'),
//           //   Text( 
//           //     '$_counter',
//           //     style: Theme.of(context).textTheme.headlineLarge,
//           //   ),
             
//           //    Text(
//           //     'Current Page Index: $currentPageIndex',
//           //     style: Theme.of(context).textTheme.bodyMedium!,  
              
//           //    ),
//           //    pages[currentPageIndex], // This is where the MainPage widget is included

//           // ],
//         // ),
//       // ),
//       bottomNavigationBar: NavigationBar(
//         // backgroundColor: Color.fromARGB(255, 214, 212, 205),
//         // selectedIndex: currentPageIndex,
//         // onDestinationSelected: (int index) {
//         //   setState(() {
//         //     currentPageIndex = index;
//         //   });
//         // },
//         destinations: const <NavigationDestination>[
//           homeDestination,
//           viewProfile,
//           settingsDestination,
//           QuizDestination,
//         ],
//         selectedIndex: currentPageIndex,
//         onDestinationSelected: (int index) {
//           setState(() {
//             currentPageIndex = index;
//           });
//         },
//       ) 
//       ,
     
//       backgroundColor: Color.fromARGB(255, 214, 212, 205),
//       // floatingActionButtonLocation: FloatingActionButtonLocation.endFloat,
//       // The build method also contains the code that builds the widget tree
//       // for this page. The widget tree is a hierarchy of widgets that describes
//       // how the UI should look. The build method is called whenever the state
//       // of the widget changes, such as when the user presses the button.
//       // The widget tree is built using a combination of layout widgets (like
//       // Column and Center) and display widgets (like Text and Icon).
//        // This trailing comma makes auto-formatting nicer for build methods.
//     );
//   }
// }
